# Generated by Django 5.2.5 on 2025-08-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskusers_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
