# Generated by Django 5.2.5 on 2025-08-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskusers_api', '0002_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
